### ISSUE TITLE
ColorEdit not saturating properly.

### ISSUE THREAD

**Issue by rickswe** [rbtnn/vim-coloredit#1]
Hello, thank you for taking the time to create this wonderful plugin. There is a strange
behavior in the function rgb2hsl line 38 of converter.vim. From my understanding no two
colors can have the same rgb.

The problem arises when you try to saturate the color '#666633' with ColorEdit
command. If you try another color like '#61afef' it works fine.

<a href="https://media1.giphy.com/media/jD515TxeOX678Qw1QY/giphy.gif"><img src="https://media1.giphy.com/media/jD515TxeOX678Qw1QY/giphy.gif" width="800" height="521"/></a>

I created this function to show the return values and it seems like it's returning the
360 hue, which is '#663333' hsl(0,33,30). You can see the hue, saturation, and lightness
[here.](https://www.w3schools.com/colors/colors_picker.asp). To replicate the problem do this:

```vim
function! Rgb2Hsl(rgb) abort
	let [r,g,b] = a:rgb
	echom 'rgb is ' a:rgb
	let hsl = coloredit#converter#rgb2hsl(r,g,b)
	echom 'return is ' hsl
	return hsl
endfunction
call Rgb2Hsl([102,102,51])
```
The return should be  ```[60,33,30]```

Try calling with another color like '#61afef' and it returns the correct hsl ```[208,
82, 66]```.

Another thing that I wanted to mention is that I don't think there is error checking
in the functions. If you call rgb2hsl and probably any other function with with random
values you will get unexpected numbers. This is probably not an issue for people who
don't call the functions and just use the menu but it may become a problem for your
script later. As a work around I created this function. I don't know if that's something
you would consider including in your code?

Return ranges 0-100 for lightness/saturation and 0-360 for hue.
```vim
function! s:CheckHslReturn(idx,val) abort
	let i = a:idx | let v = a:val
	if i == 0
		return v >= 360? 360 : v <= 0? 0 : v
	elseif i == 2 || i == 1
		return v >= 100 ? 100 : v <= 0? 0 : v
	endif
	echoerr 'Function CheckHslReturn only takes [h,s,l].'
endfunction
```

To use it, include it at the end of a function like this.
```vim
return map(coloredit#converter#rgb2hsl(r,g,b),function('<sid>CheckHslReturn'))
```

Thanks for your help

**Comment by rbtnn** [comment]
@rickalex21 Thanks you for your issue. I fixed this issue at https://github.com/rbtnn/vim-coloredit/commit/eda0cc2f7f7605305e549c7408cd177958d2e387 . Please check this.

NOTE:  This plugin convert `#663333` to `[60, 34, 30]` (round up `[60, 33.333333, 30]`) because of using a real number value as HSL when converting RGB to HSL.

**Comment by rickswe** [comment]
@rbtnn Thanks, I'll check it out when I get back on vim. I have been on nvim and it's too bad they
don't support popup windows cause I have something similar to this plugin and rewriting it would be
too much work. I think you feel the same.
